### ISSUE TITLE
Dialogtexte werden teilweise außerhalb der Spielfläche dargestellt

### ISSUE THREAD

**Issue by MathildeHoffmann** [ShaatsSucher/antonius-phaser#1]
Ist das die richtige Stelle um Bugs zu reporten? :D

Falls ja: man kann den gesprochenen Text bei mir in Firefox die meiste Zeit nicht lesen!

**Comment by cmd-johnson** [comment]
Yip, für sowas sind die GitHub Issues gedacht. Hab mir mal die Freiheit genommen den Titel etwas deskriptiver zu gestalten.

Hab das mal Valentin zugewiesen, der hatte das Problem mir gegenüber auch schonmal erwähnt und meinte er sei da dran.
