### ISSUE TITLE
Wasser Sprite

### ISSUE THREAD

**Issue by MathildeHoffmann** [ShaatsSucher/antonius-phaser#151]
evtl kleine Animation

damit der Spieler weiß, dass er Wasser an dieser Stelle holen kann.

**Comment by MathildeHoffmann** [comment]
für Szene 4  (links vom Kopf)

**Comment by cmd-johnson** [comment]
Nachdem Szene 4 gestrichen wurde gilt das für die Szenen 5 und 9
