### ISSUE TITLE
Item: Notiz des Höllenmundes

### ISSUE THREAD

**Issue by MathildeHoffmann** [ShaatsSucher/antonius-phaser#156]
Problem: Leute überspringen den Dialog des Kopfes ganz schnell und wissen nicht, was zu tun ist
Lösung: ein Item  "Notiz des Höllenmunds"   wo nochmal drauf steht, was zu tun ist

"Leider sind mir beim Gähnen ganz viele Dämonen aus dem Mund geschlüpft. 
Ich brauche deine Hilfe, die Dämonen wieder zurück in meinen Mund zu locken!
Wenn du mit ihnen sprichst, findest du bestimmt heraus, was sie für Bedürfnisse haben.
Manchen Dämonen kannst du bestimmt mit einem Gegenstand aushelfen. Nimm hierfür einen Gegenstand aus dem Beutel und ziehe ihn auf die Charaktere.
O --- >  :)  "

**Comment by spiderhat** [comment]
Können wir nicht stattdessen einfach das Intro, in dem der Kopf erklärt was los ist, mandatory machen? Ich halte das für eine bessere Lösung als ein Item einzufügen, die Leute werden ja wohl die 30 Sekunden Intro aushalten

Edit: Als eine "Hilfe"-Option finde ich das Buch aber sinnvoll.

**Comment by spiderhat** [comment]
Es gibt jetzt 3 Icons für diese Notiz/das Buch/die Hilfe in den assets/images.
Welches der 3 am besten funktioniert sollten wir dann noch gemeinsam entscheiden.

**Comment by spiderhat** [comment]
Leider nur Text ohne Zeichnung, aus zeitlichen und platztechnischen Gründen.
