### ISSUE TITLE
Nadelhuhn Sprite hat keine Füße

### ISSUE THREAD

**Issue by MathildeHoffmann** [ShaatsSucher/antonius-phaser#208]
Wenn man dem Nadelhuhn das Loch zeigt mit der eingepflanzten Nadel hat es keine Füße.
Ich hab noch ein Sprite gemacht, wo die Füße nicht abgeschnitten sind, sondern es normal da steht, das ist Frame Nummer 20.

**Comment by cmd-johnson** [comment]
@MathildeHoffmann damit das richtig aussieht, bräuchte ich noch einen Talkcycle mit Füßen, sonst verschwinden die immer, wenn sie redet.
