### ISSUE TITLE
Das fertige Bild des Malers

### ISSUE THREAD

**Issue by MathildeHoffmann** [ShaatsSucher/antonius-phaser#25]
Ein Sprite kreieren, wo der Maler was lustiges gemalt hat.

**Comment by cmd-johnson** [comment]
Der Maler malt 'die Versuchung des heiligen Antonius'

**Comment by MathildeHoffmann** [comment]
der Maler hat doch nichts lustiges gemalt sondern die Verführung des heiligen Antonius
