### ISSUE TITLE
Stirnlappen schließen

### ISSUE THREAD

**Issue by MathildeHoffmann** [ShaatsSucher/antonius-phaser#35]

**Comment by spiderhat** [comment]
Ich habe 2 spritesheets dafür hochgeladen, eins mit transparentem Hintergrund und eins zur Ansicht mit BG. Ich weiß nicht, ob das so funktioniert, wie ich mir das vorstelle, bitte meldet euch, wenn es nicht geht

**Comment by spiderhat** [comment]
Ich weiß, dass der Lappen sich eigentlich anders schließt, aber da die Datei schon jetzt viel zu groß ist und die Auflösung nicht zum Rest passt, müssten wir eigentlich alles neu machen und dafür reicht erstmal die Zeit nicht. Die "richtige" Art des Stirnlappenschließens muss also auf später verschoben werden
