### ISSUE TITLE
25 Jahre später...

### ISSUE THREAD

**Issue by MathildeHoffmann** [ShaatsSucher/antonius-phaser#36]
Neues Bild, wo man sieht, wie Gans vor dem Nadelbaum steht

(oder ganz ganz optional: alle Höllenmonster feiern Weihachten vor dem Nadelbaum)

**Comment by cmd-johnson** [comment]
Kombinieren mit dem "Vielen Dank für's Spielen"-Screen und zusammen auf Szene 11

**Comment by spiderhat** [comment]
Needle Beam spritesheet hochgeladen,
Placement: Nadelgans auf den längeren Graspart stellen
